# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/myPS/myPS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS || ORIG_REF_NAME==myPS}]

# IP: bd/myPS/ip/myPS_processing_system7_0_1/myPS_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_processing_system7_0_1 || ORIG_REF_NAME==myPS_processing_system7_0_1}]

# IP: bd/myPS/ip/myPS_axi_gpio_0_0/myPS_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_0 || ORIG_REF_NAME==myPS_axi_gpio_0_0}]

# IP: bd/myPS/ip/myPS_axi_gpio_0_1/myPS_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_1 || ORIG_REF_NAME==myPS_axi_gpio_0_1}]

# IP: bd/myPS/ip/myPS_axi_gpio_0_2/myPS_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_2 || ORIG_REF_NAME==myPS_axi_gpio_0_2}]

# IP: bd/myPS/ip/myPS_axi_gpio_0_3/myPS_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_3 || ORIG_REF_NAME==myPS_axi_gpio_0_3}]

# IP: bd/myPS/ip/myPS_processing_system7_0_axi_periph_0/myPS_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==myPS_processing_system7_0_axi_periph_0}]

# IP: bd/myPS/ip/myPS_rst_processing_system7_0_100M_0/myPS_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==myPS_rst_processing_system7_0_100M_0}]

# IP: bd/myPS/ip/myPS_xbar_0/myPS_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_xbar_0 || ORIG_REF_NAME==myPS_xbar_0}]

# IP: bd/myPS/ip/myPS_axi_gpio_4_0/myPS_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_4_0 || ORIG_REF_NAME==myPS_axi_gpio_4_0}]

# IP: bd/myPS/ip/myPS_axi_gpio_4_1/myPS_axi_gpio_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_4_1 || ORIG_REF_NAME==myPS_axi_gpio_4_1}]

# IP: bd/myPS/ip/myPS_auto_pc_0/myPS_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_auto_pc_0 || ORIG_REF_NAME==myPS_auto_pc_0}]

# XDC: bd/myPS/ip/myPS_processing_system7_0_1/myPS_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_processing_system7_0_1 || ORIG_REF_NAME==myPS_processing_system7_0_1}] {/inst }]/inst ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_0_0/myPS_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_0 || ORIG_REF_NAME==myPS_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_0_0/myPS_axi_gpio_0_0_ooc.xdc

# XDC: bd/myPS/ip/myPS_axi_gpio_0_0/myPS_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_0 || ORIG_REF_NAME==myPS_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_0_1/myPS_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_1 || ORIG_REF_NAME==myPS_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_0_1/myPS_axi_gpio_0_1_ooc.xdc

# XDC: bd/myPS/ip/myPS_axi_gpio_0_1/myPS_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_1 || ORIG_REF_NAME==myPS_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_0_2/myPS_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_2 || ORIG_REF_NAME==myPS_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_0_2/myPS_axi_gpio_0_2_ooc.xdc

# XDC: bd/myPS/ip/myPS_axi_gpio_0_2/myPS_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_2 || ORIG_REF_NAME==myPS_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_0_3/myPS_axi_gpio_0_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_3 || ORIG_REF_NAME==myPS_axi_gpio_0_3}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_0_3/myPS_axi_gpio_0_3_ooc.xdc

# XDC: bd/myPS/ip/myPS_axi_gpio_0_3/myPS_axi_gpio_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_0_3 || ORIG_REF_NAME==myPS_axi_gpio_0_3}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_rst_processing_system7_0_100M_0/myPS_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==myPS_rst_processing_system7_0_100M_0}]

# XDC: bd/myPS/ip/myPS_rst_processing_system7_0_100M_0/myPS_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myPS_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==myPS_rst_processing_system7_0_100M_0}]

# XDC: bd/myPS/ip/myPS_rst_processing_system7_0_100M_0/myPS_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/myPS/ip/myPS_xbar_0/myPS_xbar_0_ooc.xdc

# XDC: bd/myPS/ip/myPS_axi_gpio_4_0/myPS_axi_gpio_4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_4_0 || ORIG_REF_NAME==myPS_axi_gpio_4_0}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_4_0/myPS_axi_gpio_4_0_ooc.xdc

# XDC: bd/myPS/ip/myPS_axi_gpio_4_0/myPS_axi_gpio_4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_4_0 || ORIG_REF_NAME==myPS_axi_gpio_4_0}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_4_1/myPS_axi_gpio_4_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_4_1 || ORIG_REF_NAME==myPS_axi_gpio_4_1}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_axi_gpio_4_1/myPS_axi_gpio_4_1_ooc.xdc

# XDC: bd/myPS/ip/myPS_axi_gpio_4_1/myPS_axi_gpio_4_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==myPS_axi_gpio_4_1 || ORIG_REF_NAME==myPS_axi_gpio_4_1}] {/U0 }]/U0 ]]

# XDC: bd/myPS/ip/myPS_auto_pc_0/myPS_auto_pc_0_ooc.xdc

# XDC: bd/myPS/myPS_ooc.xdc
