# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.cache/wt [current_project]
set_property parent.project_path C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/myPS.bd
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_processing_system7_0_1/myPS_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_0/myPS_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_0/myPS_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_0/myPS_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_1/myPS_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_1/myPS_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_1/myPS_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_2/myPS_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_2/myPS_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_2/myPS_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_3/myPS_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_3/myPS_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_0_3/myPS_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_rst_processing_system7_0_100M_0/myPS_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_rst_processing_system7_0_100M_0/myPS_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_rst_processing_system7_0_100M_0/myPS_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_xbar_0/myPS_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_4_0/myPS_axi_gpio_4_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_4_0/myPS_axi_gpio_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_4_0/myPS_axi_gpio_4_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_4_1/myPS_axi_gpio_4_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_4_1/myPS_axi_gpio_4_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_axi_gpio_4_1/myPS_axi_gpio_4_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/ip/myPS_auto_pc_0/myPS_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/myPS_ooc.xdc]
set_property is_locked true [get_files C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/myPS.bd]

read_vhdl -library xil_defaultlib {
  C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/new/mux.vhd
  C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/new/steeringPWM.vhd
  C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/new/speedPWM.vhd
  C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/new/rfChangeDetect.vhd
  C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/new/myClkDivider.vhd
  C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/bd/myPS/hdl/myPS_wrapper.vhd
  C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/sources_1/new/top.vhd
}
read_xdc C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/constrs_1/new/pins.xdc
set_property used_in_implementation false [get_files C:/Users/Joey/Desktop/rfTracker/rf_project/rf_project.srcs/constrs_1/new/pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7z020clg484-2
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
